apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-helm
spec:
  destination:
    namespace: example-helm
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/bgd-helm-chart
    repoURL: https://github.com/GuilhermeCamposo/demo_gitops
    targetRevision: main
    helm:
      valueFiles:
        - custom_values_1/values.yaml
  sources: []
  project: demo-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
