apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
spec:
  destination:
    namespace: example-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/bgd
    repoURL: https://github.com/GuilhermeCamposo/demo_gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
