- name: Install GitOps Demo
  hosts: localhost
  vars:
    verify_tls: false
    insecure_skip_tls_verify: true
  tasks:
    - name: Check Required Parameters
      ansible.builtin.fail:
        msg: "This play requires 'server' and 'token' to be defined"
      when:
        - (server is not defined) or (token is not defined) or (server is none) or (token is none)
      ignore_errors: false
      tags: [argocd]

    - name: Set domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"
      tags: [argocd]

    - name: Set Subdomain
      ansible.builtin.set_fact:
        route_subdomain: "apps.{{ domain }}"
      tags: [argocd]

    - name: Include ArgoCD
      ansible.builtin.include_role:
        name: argocd
        apply:
          tags: [argocd]
      tags: [argocd]
